/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "../STM32F103_DRIVER/01-LIB/01-STD_TYPES/STD_TYPES.h"

#include "../STM32F103_DRIVER/02-MCAL/01-RCC/RCC_interface.h"
#include "../STM32F103_DRIVER/02-MCAL/02-GPIO/GPIO_interface.h"

#include "FreeRTOS.h"
#include "FreeRTOSConfig.h"
#include "task.h"
#include "semphr.h"
#include "queue.h"

#define STACK_SIZE 100


void slaveFCN(void* vPTR);
void MasterFCN(void* vPTR);


u8 BTN_currentState, BTN_prevState ;

/*	Task Creation	*/
TaskHandle_t LEDHandler = NULL;
TaskHandle_t ButtonHandler = NULL;

/*	Semaphores	*/
QueueHandle_t	xQueue = NULL;


/*************** Commands	*************/
u8 OFF = 0,
ON = 1 ,
TOGG = 3
;



int main(void)
{
	RCC_voidInitSysClocks();



    /* Create the task, storing the handle. */
    xTaskCreate(slaveFCN,"Master Generate CMDs",  STACK_SIZE, NULL , 2,&LEDHandler );
    xTaskCreate(MasterFCN,"Slave Receive CMDs",  STACK_SIZE, NULL , 1,&ButtonHandler );

    /*	Create Semaphore		*/
    xQueue = xQueueCreate(10, sizeof(u8));	// 10 element with sizez u8 for each elemnet

    /*			START SCHEDULER		*/
    vTaskStartScheduler();

    /* Loop forever */
	for(;;);
}

void slaveFCN(void* vPTR)
{
	RCC_voidEnableClock(RCC_APB2, PORTA);
	GPIO_voidSetPinDirection(PORTA, PIN2, GPIO_OUTPUT_10MHZ_PUSH_PULL);
	u8 cmdReceived = 0 ;

	while(1)
	{
		xQueueReceive(xQueue, &cmdReceived	,(TickType_t)5) ;
		if(cmdReceived != TOGG)
			GPIO_voidSetPinValue(PORTA,PIN2,cmdReceived);
		else
			GPIO_voidTogglePinValue(PORTA, PIN2);
		vTaskDelay(10);
	}

}
void MasterFCN(void* vPTR)
{

	while(1)
	{
		xQueueSend(xQueue,&ON,(TickType_t)5);
		vTaskDelay(15);
		xQueueSend(xQueue,&OFF,(TickType_t)5);
		vTaskDelay(15);
		xQueueSend(xQueue,&TOGG,(TickType_t)5);
		vTaskDelay(15);
		xQueueSend(xQueue,&TOGG,(TickType_t)5);
		vTaskDelay(15);

	}
}
