/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#define RCC_BASE	0x40021000
#define EXTI_BASE 	0x40010400
#define AFIO_BASE 	0x40010000
#define PORTA_BASE 	0x40010800
#define NVIC_BASE   0xE000E100

#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE+0x18)
#define RCC_CFGR	*(volatile uint32_t *)(RCC_BASE + 0x04)


#define EXTI_IMR	*(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_EMR	*(volatile uint32_t *)(EXTI_BASE + 0x04)
#define EXTI_RTSR	*(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR		*(volatile uint32_t *)(EXTI_BASE + 0x14)


#define NVIC_ISER	*(volatile uint32_t *)(NVIC_BASE + 0x000)
#define EXTI0_IRQ	6

#define AFIO_EXTICR1	*(volatile uint32_t *)(AFIO_BASE + 0x08)

#define GPIO0_CRL	*(volatile uint32_t *)(PORTA_BASE + 0x00)
#define GPIO0_CRH	*(volatile uint32_t *)(PORTA_BASE + 0x04)
#define GPIO_ODR	*(volatile uint32_t *)(PORTA_BASE + 0x0C)




void CLK_init();
void INT_init();
void AFIO_init();
void GPIO_Init();

int main(void)
{
	CLK_init() ;
	AFIO_init () ;
	GPIO_Init ();
	INT_init () ;
	while(1)
	{

	}
}
void CLK_init()
{
	// EXTI --> APB2
	// 1- CONFIG CLK SRC INTERNAL 8 MHZ
	RCC_CFGR &= ~(0b11 << 0) ;  
	// 2- CONFIG AHB PRESCALER
	RCC_CFGR &= ~(0b1111 << 4) ; 
	// 3- CONFIG APB2 CLK
	RCC_CFGR &= ~(0b111 << 11) ;
	// ENABLE CLK TO PERPHERIAL
	// 1- AFIO ON APB2
	RCC_APB2ENR |= (1<< 0) ;
	// 2- GPIO PORT A ON APB2
	RCC_APB2ENR |= (1<< 2) ;
}
void INT_init()
{
	// PA0 --> EXTI0
	// AFIO INIT EXTI0[3:0] bits in AFIO_EXTICR1 register
	// Enable Input Line
	EXTI_IMR |= (1 << 0) ;
	// Set Rising or Falling Edge and reset Event Trigger
	EXTI_EMR &= ~(1<<0);
	EXTI_RTSR |= (1<< 0);
	// SET NVIC Controller
	NVIC_ISER |= (1 << EXTI0_IRQ);
}

void AFIO_init()
{
	// PA[x] pin
	AFIO_EXTICR1 &= ~(0b111 << 0) ; 
}

void GPIO_Init()
{
	/*		PIN A0 INIT AS INPUT FLOATING	*/
	// INPUT
	GPIO0_CRL &= ~(0b11 << 0) ;
	// INPUT FLOAT
	GPIO0_CRL |= (0b01 << 2) ;
	/*		PIN A13 AS OUTPUT	*/
	GPIO0_CRH |= (0b10 << 20) ;
	GPIO0_CRH &= ~(0b11 << 22) ; 
}

// IRQ HANDLER
void EXTI0_IRQHandler()
{
	// CLEAR PENDING FLAG
	EXTI_PR |= (1<< 0);
	// Toggle Lamp
	GPIO_ODR ^= (1<<13);

}
